### ISSUE TITLE
swToolboxURL path does not match the folder structure in sw-toolbox

### ISSUE THREAD

**Issue by mitjarobic** [PolymerElements/platinum-sw#106]
var swToolboxURL = new URL('../sw-toolbox/sw-toolbox.js', global.params.get('baseURI')).href;

should be:

 var swToolboxURL = new URL('../sw-toolbox/build/sw-toolbox.js', global.params.get('baseURI')).href;

**Comment by jeffposnick** [comment]
This should be resolved on `sw-toolbox`'s end: https://github.com/GoogleChrome/sw-toolbox/issues/143

**Comment by jeffposnick** [comment]
It's fixed upstream in `sw-toolbox`.
