### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by addyosmani** [PolymerElements/platinum-sw#29]
We currently rely on master in a few places, which can be..problematic :) Can we tag a release?

**Comment by jeffposnick** [comment]
Currently blocked on using/tagging v1.0.x by a recurrence of https://github.com/PolymerElements/iron-component-page/issues/17

Once that's resolved, I'll file a PR for https://github.com/PolymerElements/platinum-sw/tree/1.0.0

**Comment by jeffposnick** [comment]
https://github.com/PolymerElements/platinum-sw/releases/tag/v1.0.0
