### ISSUE TITLE
Link to documentation in README is broken

### ISSUE THREAD

**Issue by addyosmani** [PolymerElements/platinum-sw#30]
https://polymerelements.github.io/platinum-sw/index.html

**Comment by jeffposnick** [comment]
This was fixed by https://github.com/PolymerElements/platinum-sw/commit/1229c8970399eea2c5e1366cf1756b8a9dbde3b7 now that `gp.sh` has been [updated](https://github.com/Polymer/tools/commit/a89524322d8ad90f7d999df9dad53408d6264e33).
