### ISSUE TITLE
Resolve issues with CI tests

### ISSUE THREAD

**Issue by jeffposnick** [PolymerElements/platinum-sw#37]

**Comment by jeffposnick** [comment]
The current failures seem to be in Linux Chrome, along the lines of

Linux chrome             ✖ test/platinum-sw-fetch/ » Service Worker Fetch Handlers » the same-origin custom fetch handler is used when the path matches

**Comment by jeffposnick** [comment]
I can now reproduce a similar failure in OS X Chrome Version 46.0.2464.0 canary (64-bit), which makes it easier to debug what's going on.

I think the failure can be traced back to the incomplete implementation of `Cache.prototype.addAll()` in the Canary branch of Chrome. That's causing problems with https://github.com/GoogleChrome/sw-toolbox/blob/master/lib/sw-toolbox.js#L35, which previously worked fine with the `Cache.prototype.addAll()` polyfill, but keeps the service worker stuck in the `installing` state when attempting to use the incomplete native implementation.

@wibblymat, I'm assuming you don't have to do anything with `sw-toolbox`, and this will just take care of itself once Chrome Canary gets a complete native `Cache.prototype.addAll()`, but I'm CC:ing you as a heads-up. Changing the production library to work around bugs in the current Chrome Canary doesn't seem like the best precedent.

**Comment by jeffposnick** [comment]
And digging even further, the underlying issue is that `Cache.prototype.addAll([])` never resolves in the current Chrome Canary. It does appear to be functional if you pass in at least one valid `Request`/URL string, but `sw-toolbox` passes in an empty `[]` if `options.preCacheItems` is `[]`.

I'll file a bug against Chromium.

**Comment by jeffposnick** [comment]
https://code.google.com/p/chromium/issues/detail?id=513818

**Comment by wibblymat** [comment]
Thanks for the heads up. Looks like that issue is getting fixed, so I assume that it will never make it to stable.
