### ISSUE TITLE
Ensure that developers know when they're using an unsupported set of parameters

### ISSUE THREAD

**Issue by jeffposnick** [PolymerElements/platinum-sw#47]
E.g. defining a `<platinum-sw-fetch>` without a `handler` attribute is meaningless, but there currently isn't any error communicated back to the developer. It's effectively a silent failure.

There is [precedent elsewhere](https://github.com/PolymerElements/platinum-sw/blob/faf7d8863cf30e8876264ff68c121f32783c903a/platinum-sw-register.html#L328) in the project to use `console.error()` to let developers know about this sort of thing, but there's a fine line between alerting developers and spamming the console. It's also not clear how many developers know to check the console.

**Comment by addyosmani** [comment]
:+1: for some clear warning here. I personally wouldn't mind another `console.error` being logged, but it depends on the quantity of console spamming as a whole. Looking through the source I think this is minimal atm.
