### ISSUE TITLE
Docs: clarify that default cache strategy is applied to local and remote resources

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/platinum-sw#48]
The docs say:

"This is enough to have all of the (local) resources your site uses cached at runtime."

My assumption was that I could't use this for remote resources. From @jeffposnick's research:

When using `<platinum-sw-cache default-cache-strategy="...">`, that handler will be applied to all requests, both same or cross-origin.

**Comment by addyosmani** [comment]
That's been my experience too (though I haven't touched too much in the last week or two). +1 for docs.
