### ISSUE TITLE
Implicit precache limit

### ISSUE THREAD

**Issue by csmith932** [PolymerElements/platinum-sw#53]
The platinum-sw registration process passes parameters to the service worker via the sw-import.js query string. There's a de facto limit on the number of characters in a URL (e.g. 2,083 for IE), which means for practical purposes that the number of files in the precache list is limited to perhaps a few dozen (depending on individual resource path lengths). Possible resolution is to send the precache manifest resource name via the query string and sw-import.js or service-worker.js can fetch the manifest and extract the precache list itself.

**Comment by Mygod** [comment]
+1
Just got this error: `Service worker error: NetworkError: Failed to register a ServiceWorker: A bad HTTP response code (414) was received when fetching the script.`

**Comment by jeffposnick** [comment]
Thanks for raising an issue to track this. I'm working on a refactoring of how build-time configuration is processed by `<platinum-sw-cache>` and should address this edge case as part of that.
