### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wibblymat** [PolymerElements/platinum-sw#56]
I got bit by the vulcanization problem that #51 solves. We should tag a new release so that people can get that. @jeffposnick

**Comment by jeffposnick** [comment]
I just merged https://github.com/PolymerElements/platinum-sw/pull/55, and I was going to tag `1.2.0`, but I think I'm going to put together something quick to help with https://github.com/PolymerElements/platinum-sw/issues/53 before tagging a new release. Stay tuned.
