### ISSUE TITLE
Fix path to sw-toolbox

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/platinum-sw#59]
Could you fix path `../sw-toolbox/sw-toolbox.js` to `/sw-toolbox/sw-toolbox.js`? 

https://github.com/PolymerElements/platinum-sw/blob/master/bootstrap/sw-toolbox-setup.js#L12

I need correct path for https://github.com/smysnk/gulp-rev-all

I am using gulp-rev-all in https://github.com/StartPolymer/polymer-starter-kit-plus

PSK have `bootstrap` dir in `elements` dir and `sw-toolbox` dir in root.

**Comment by JosefJezek** [comment]
I create task for fix path to sw-toolbox.js `../../sw-toolbox/sw-toolbox.js`

What solution is right?

**Comment by jeffposnick** [comment]
No, I don't think that hardcoding an absolute path pointing to the top-level directory is the right thing to do. There are deployments in which developers might not have access to the top-level directory, and using a relative path is friendlier in general.

Moving `sw-toolbox` into the appropriate location as part of your build process makes the most sense. That's what's going on in the "official" Polymer Starter Kit project: https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L106
