### ISSUE TITLE
opt-in option to fallback network-first into a cache-first pattern on slow networks

### ISSUE THREAD

**Issue by isaldarriaga** [PolymerElements/platinum-sw#60]
As a developer, i'd like to setup the platinum-sw element to use the network-first pattern, but the element to automatically fallback into a cache-first pattern if the connection is alive and the average TTFB or RTT (latency) of the browsing session is higher or equal to a "pre-defined" threshold the developer sets, so the user benefit of a better UX (instant rendering) instead of a slow download of the most up-to-date content as currently happen in the network-first pattern under GPRS, 2G or 3G.

As the pre-defined threshold the developer should be able to set either the averaged TTFB (Time To First Byte) of a particular resource of its app under a critical network condition (GPRS, 2G, 3G or a mid-point), the average TTFB of all the resources that belongs to the CRP (Critical Rendering Path), or the expected RTT (Round Trip Time) as displayed in chrome dev tools (in network throttling: custom or predefined).

The element should be able to calculate the average TTFB (responseStart-requestStart) by using the resource timing API and looping through all the recorded metrics available (window.performance.getEntriesByType("resource")), or to calculate the average RTT a similar way. 

BTW, I don't know how to measure the RTT with the API, or if really possible, maybe the browser is able to know that with the help of a lower level API :|
The idea behind using RTT instead of TTFB, is just ergonomics. TTFB should be measured, while RTT can be just assumed as valid according to the dev tools (i.e. RTT for 2G, 3G, etc. or a mid point).

If the measured TTFB/RTT is greater or equal to the threshold, the element retrieves everything from the cache, not the network, as if the user is offline.

The developer accepts the trade (user in slower networks cannot update the app), and should design accordingly.

************
Another proposed feature is the platinum-sw element to "heal itself" and determine the proper threshold along the time, this way:
- record the download time of all the resources that belongs to the CRP (anything downloaded before the domInteractive, or the last img's onload event - developer decides) 
- record the TTFB/RTT of each resource that belongs to the CRP
- calculate the total download time of the CRP (sum)
- calculate the average TTFB/RTT of the CRP
- save the previous sample as a single record in the local storage (averageTTFB, averageRTT, downloadTime, URL)
- once the localStorage have a good sample (see later) and the unload event of the page is caught, the element does the polynomial regression (estimation) of the download time using the current TTFB/RTT of the last downloaded resources, i.e. non cached resources. The element now have the estimated download time of the full page.
- At this point the element could decide if the pre-defined TTFB/RTT threshold by the developer is the metric needed to determine the best UX, or the recorded sample in localStorage is the best source to do it. If after interpolating the download times recorded in localStorage using the pre-defined TTFB/RTT, the returned value (download time) is +-1% different to 1000ms (RAIL metric), then the polynomial regression should be the method to use.

This logic assumes downloading the page in more than 1000 ms is better than having the most up-to-date content, and the user at some point will get connected to a better network.

goodness of the sample: as long as you determine the correct coefficients of a 4th degree polynomial function based on the sampled data, they fully describe the relationship between TTFB and the expected download time of a HTTP/TCP resource. I have verified it and compared it to other models (linear, and 1st to 3rd degree polys), and 4th degree polynomial is better. Accuracy is very high. The drawback: the element should include logic to solve the equation, and precisely calculate coefficients between orders of 10 powered to -9 to 10 powered -7 for the polynomial function to work with the precision desired.

******
Alternative solution: Use checksums or another method to determine if the content in the server has changed. If not changed, retrieve it from cache.

******
References:
resource timing API: http://www.w3.org/TR/resource-timing/
http://www.w3.org/TR/navigation-timing/#sec-navigation-timing-interface

Let me know if this is too crazy or there's a better way to solve the problem.

**Comment by jeffposnick** [comment]
`<platinum-sw-cache>` is a wrapper around @wibblymat's `sw-toolbox` project, which implements all of the caching algorithms. I'd suggest using that [issue tracker](https://github.com/GoogleChrome/sw-toolbox/issues) for this type of request.

Regarding your checksum idea, there's an alternative project, [`sw-precache`](https://github.com/GoogleChrome/sw-precache), which integrates with a build process to generate a service worker script that is cache-first and relies on MD5 hashes to detect updates. It doesn't play nicely with `<platinum-sw-cache>`, but you can combine `sw-precache` and `sw-toolbox` to handle cache-first requests for local resources and an alternative runtime strategy for remote resources.

There's a real-world example of `sw-precache` + `sw-toolbox` in the Google I/O 2015 web app's [source code](https://github.com/GoogleChrome/ioweb2015).
