### ISSUE TITLE
Unclear how to use platinum-sw-fetch

### ISSUE THREAD

**Issue by benknight** [PolymerElements/platinum-sw#75]
How would you use these elements such that `networkFirst` handler on all resources by default, and `networkOnly` on requests to `http://192.168.*.*`?  I tried this but it doesn't work:

```
<platinum-sw-register auto-register>
	<platinum-sw-fetch handler="networkOnly" origin="http://192\.168\..+\..+">
	<platinum-sw-cache></platinum-sw-cache>
</platinum-sw-register>
```

**Comment by jeffposnick** [comment]
You're mostly there. The current implementation requires that you always set `path`, even when using `origin`. There's an warning message that gets logged in the JS console, but that's easy to miss:

![image](https://cloud.githubusercontent.com/assets/1749548/10947816/54d0a348-82f8-11e5-8935-28eaffda9f40.png)

So something like
```js
<platinum-sw-register auto-register>
    <platinum-sw-fetch path="/(.*)" handler="networkOnly" origin="http://192\.168\..+\..+">
    <platinum-sw-cache></platinum-sw-cache>
</platinum-sw-register>
```
should give you the behavior you want.

This is fairly developer unfriendly, and I think it would be reasonable to default to `path="/(.*)"` when `origin` is set in a future release of `<platinum-sw-fetch>`.

**Comment by benknight** [comment]
I did eventually figure that out, thanks!
