### ISSUE TITLE
Bad default baseUri in Firefox

### ISSUE THREAD

**Issue by jeffposnick** [PolymerElements/platinum-sw#81]
See the thread starting at https://twitter.com/wanderview/status/667716582630662144 for context.

The relevant code is at https://github.com/PolymerElements/platinum-sw/blob/master/platinum-sw-register.html#L101

My current hypothesis is that polyfilled HTML Imports in Firefox is causing `document.currentScript` to be set to the host page rather than the underlying Polymer element, but I need to experiment some more.

CC: @wanderview, and @wibblymat since `document.currentScript` is also being used in https://github.com/PolymerElements/platinum-push-messaging/blob/master/platinum-push-messaging.html#L20

**Comment by wanderview** [comment]
Can you use a <base> tag in your polyfill?  I think that would let you override the .baseURI getter value.

**Comment by jeffposnick** [comment]
Finally got a chance to dig into this, and it turns out that there's already a solution provided by the HTML Imports polyfill: [`document._currentScript`](https://github.com/webcomponents/webcomponentsjs/blob/88240ba9ef4cebb1579e07f7888c7b58ec017a39/src/HTMLImports/base.js#L31)

I'll put together a PR to switch to using that.
