### ISSUE TITLE
platinum-sw-fetch event handler for POST requests

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/platinum-sw#82]
_From @ioantomulesei on November 27, 2015 12:23_

I'm using platinum-sw-fetch component to map fetch requests to handlers inside service workers. It works well for "GET" requests but not for "POST" requests. One of my use case is returning fixture data for my requests.
After digging polymer code, I found that are defined routes (by sw-toolbox library) only for "GET" requests:
```javascript

sw-toolbox-setup.js
...
 if (typeof handler === 'function') {
        global.toolbox.router.get(routeParams[0], handler, originParam);
      } else {
        console.error('Unable to register sw-toolbox route: ', routeParams);
      }
...
```

Is there an option for registering handlers for "POST" request?

_Copied from original issue: Polymer/polymer#3097_

**Comment by ebidel** [comment]
_From @adelarosab on November 29, 2015 23:56_

Hi @ioantomulesei,

This is just a suggestion because I'm not part of the Google team, but I think this issue should be reported in https://github.com/PolymerElements/platinum-sw/issues (which is the repo of platinum elements).

**Comment by ebidel** [comment]
cc @jeffposnick @wibblymat

**Comment by wibblymat** [comment]
@ioantomulesei The built-in handlers are not useful for anything except GET requests.

The `CacheStorage` API that is used by service workers only allows you to store GET requests, and the only built-in handler that doesn't use the cache is `networkOnly` - the same as not having a handler at all.

There are times that you might want to handle POST requests, and the underlying `sw-toolbox` library that we use can deal with that if you use a custom handler, but for the moment `<platinum-sw>` is aimed at the simpler cases.

For now, if you want to do something more complex you will have to drop to a lower level of abstraction.

**Comment by jeffposnick** [comment]
That lower level of abstraction could be provided in a standalone JavaScript file that makes calls to `toolbox.router.post(...)`, and then gets included along with your existing service worker config via [`<platinum-sw-import-script>`](https://elements.polymer-project.org/elements/platinum-sw?active=platinum-sw-import-script).
