### ISSUE TITLE
How to handle dynamic URLs

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/platinum-sw#87]
How to handle dynamic URLs `/users`, `/users/:name`, `/contact` in PSK?

https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L206

**Comment by jeffposnick** [comment]
Any URL that doesn't match an explicit route will use the handler defined by [`defaultCacheStrategy`](https://elements.polymer-project.org/elements/platinum-sw#defaultCacheStrategy).

If you need a specific, non-default handler for a given URL pattern, you can use [`<platinum-sw-fetch>`](https://elements.polymer-project.org/elements/platinum-sw?active=platinum-sw-fetch). The `path` attribute takes in Express-style routes, as illustrated in the example from the docs:

```html
<platinum-sw-register auto-register>
  <platinum-sw-import-script href="custom-fetch-handler.js"></platinum-sw-import-script>
  <platinum-sw-fetch handler="customFetchHandler"
                     path="/(.*)/customFetch"></platinum-sw-fetch>
</platinum-sw-register>
```
